spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testa
    username: testa
    password: testa1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
